---
- hosts: web
  become: yes
  vars:
    common_hostname: test.histudy.jp
    common_ssh_use_geoip_filter: true 
    common_ssh_allow_countries:
      - JP
      - US
    common_groups:
      - name: www-data
    common_users:
      "{{ users }}"

  roles:
    - role: common
    - role: nginx
  tasks:
    - name: Fix document root permission
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: a-x,go+wx,u+w,a+rX,g+s

    - name: Adjust ufw for circle CI
      ufw:
        rule: allow
        port: 22
        proto: tcp
