---
- hosts: web
  become: yes
  vars:
    common_hostname: test.histudy.jp
    common_ssh_use_geoip_filter: true 
    common_ssh_allow_countries:
      - JP
      - US
    common_groups:
      - name: www-data
    common_users:
      "{{ users }}"
    certbot_create_if_missing: yes
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_install_method: snap
    certbot_create_method: webroot
    certbot_admin_email: autumnsky64@gmail.com
    certbot_certs:
    - domains:
        - test.histudy.jp
    certbot_auto_renew: true
    certbot_auto_renew_hour: "3"
    certbot_auto_renew_minute: "30"
    nginx_vhosts:
      - name: static-ssl
        server_name: test.histudy.jp
        index: "index.html"
        access_log: /var/log/nginx/ssl.access.log
        error_log: /var/log/nginx/ssl.error.log
        document_root: "/var/www/html"
        client_max_body_size: 16M
        ssl:
          certificate: /etc/letsencrypt/live/test.histudy.jp/cert.pem
          certificate_key: /etc/letsencrypt/live/test.histudy.jp/privkey.pem
          trusted_certificate: /etc/letsencrypt/live/test.histudy.jp/chain.pem
          session_timeout: "1d"
          session_cache: "shared:SSL:50m"
          session_tickets: false
          hsts: "max-age=15768000; includeSubDomains;"
          stapling: true
          stapling_verify: true

  roles:
    #- role: common
    - role: nginx
    - geerlingguy.certbot

  # キャッシュの関係か certbot ロールでのインストールが通らない
  pre_tasks:
    - name: Install snapd
      apt:
        name:
          - snapd
        state: absent
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true

  tasks:
    - name: Fix document root permission
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: a-x,go+wx,u+w,a+rX,g+s

    - name: Adjust ufw for circle CI
      ufw:
        rule: allow
        port: "22"
        proto: tcp
